language: cpp
os:
  - linux
  - osx
compiler:
    - gcc
    - clang
before_install: travis/before_install.sh
install: travis/install.sh
before_script:
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
script:
    - cmake .
    - make
